# Welcome to Jupyter!

This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

Outline of some basics:

* [Notebook Basics](../examples/Notebook/Notebook%20Basics.ipynb)
* [IPython - beyond plain python](../examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb)
* [Markdown Cells](../examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)
* [Rich Display System](../examples/IPython%20Kernel/Rich%20Output.ipynb)
* [Custom Display logic](../examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)
* [Running a Secure Public Notebook Server](../examples/Notebook/Running%20the%20Notebook%20Server.ipynb#Securing-the-notebook-server)
* [How Jupyter works](../examples/Notebook/Multiple%20Languages%2C%20Frontends.ipynb) to run code in different languages.

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:

    # first, always upgrade pip!
    pip install --upgrade pip
    pip install --upgrade ipython jupyter

Start the notebook in the tutorial directory:

    cd ipython-in-depth
    jupyter notebook

In [1]:
import numpy as np
np.random.randint(-10,10,5)


array([ 4,  9,  8, -4,  2])

In [2]:
np.random.randint(-10,10,5)


array([  3,   1,   1, -10,   5])

In [3]:
arr = [23,34,5,6,6,6,66,6]
aar+2


NameError: name 'aar' is not defined

In [4]:
arr+2


TypeError: can only concatenate list (not "int") to list

In [6]:
arr = np.array([12,1,22,122,21212])
arr1=arr+2
arr1


array([   14,     3,    24,   124, 21214])

In [7]:
arr/2


array([6.0000e+00, 5.0000e-01, 1.1000e+01, 6.1000e+01, 1.0606e+04])

In [8]:
arr*2

array([   24,     2,    44,   244, 42424])

In [10]:
arr = np.array([19,20,23,22,44,33,22,11])
arr/2


array([ 9.5, 10. , 11.5, 11. , 22. , 16.5, 11. ,  5.5])

In [11]:
arr+2

array([21, 22, 25, 24, 46, 35, 24, 13])

In [12]:
   np.log(arr)

array([2.94443898, 2.99573227, 3.13549422, 3.09104245, 3.78418963,
       3.49650756, 3.09104245, 2.39789527])

In [20]:
  arr = np.linespace(10,10,2)
    

AttributeError: module 'numpy' has no attribute 'linespace'

In [23]:
arr = np.linspace(0,20,8,5)
arr

    

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [25]:
ar = np.random.rand(5,5)
ar

array([[0.15016113, 0.26246404, 0.05793916, 0.46003835, 0.57547063],
       [0.31438024, 0.95647875, 0.12822561, 0.82007406, 0.35572039],
       [0.57765706, 0.55386432, 0.99438075, 0.31878782, 0.9371645 ],
       [0.9881976 , 0.3178434 , 0.24850592, 0.19427044, 0.91950291],
       [0.79091829, 0.7361304 , 0.72227276, 0.71883457, 0.48075889]])

In [26]:
ar+3
ar

array([[0.15016113, 0.26246404, 0.05793916, 0.46003835, 0.57547063],
       [0.31438024, 0.95647875, 0.12822561, 0.82007406, 0.35572039],
       [0.57765706, 0.55386432, 0.99438075, 0.31878782, 0.9371645 ],
       [0.9881976 , 0.3178434 , 0.24850592, 0.19427044, 0.91950291],
       [0.79091829, 0.7361304 , 0.72227276, 0.71883457, 0.48075889]])

In [27]:
ar+10
ar

array([[0.15016113, 0.26246404, 0.05793916, 0.46003835, 0.57547063],
       [0.31438024, 0.95647875, 0.12822561, 0.82007406, 0.35572039],
       [0.57765706, 0.55386432, 0.99438075, 0.31878782, 0.9371645 ],
       [0.9881976 , 0.3178434 , 0.24850592, 0.19427044, 0.91950291],
       [0.79091829, 0.7361304 , 0.72227276, 0.71883457, 0.48075889]])

In [28]:
ar = ar+4

In [29]:
ar


array([[4.15016113, 4.26246404, 4.05793916, 4.46003835, 4.57547063],
       [4.31438024, 4.95647875, 4.12822561, 4.82007406, 4.35572039],
       [4.57765706, 4.55386432, 4.99438075, 4.31878782, 4.9371645 ],
       [4.9881976 , 4.3178434 , 4.24850592, 4.19427044, 4.91950291],
       [4.79091829, 4.7361304 , 4.72227276, 4.71883457, 4.48075889]])

In [30]:
ar/4
ar

array([[4.15016113, 4.26246404, 4.05793916, 4.46003835, 4.57547063],
       [4.31438024, 4.95647875, 4.12822561, 4.82007406, 4.35572039],
       [4.57765706, 4.55386432, 4.99438075, 4.31878782, 4.9371645 ],
       [4.9881976 , 4.3178434 , 4.24850592, 4.19427044, 4.91950291],
       [4.79091829, 4.7361304 , 4.72227276, 4.71883457, 4.48075889]])

In [31]:
 ar =ar/2
 

IndentationError: unexpected indent (<ipython-input-31-64f676e37c88>, line 2)

In [32]:
ar 

array([[4.15016113, 4.26246404, 4.05793916, 4.46003835, 4.57547063],
       [4.31438024, 4.95647875, 4.12822561, 4.82007406, 4.35572039],
       [4.57765706, 4.55386432, 4.99438075, 4.31878782, 4.9371645 ],
       [4.9881976 , 4.3178434 , 4.24850592, 4.19427044, 4.91950291],
       [4.79091829, 4.7361304 , 4.72227276, 4.71883457, 4.48075889]])

In [38]:
ar = ar/2
ar


array([[1.03754028, 1.06561601, 1.01448479, 1.11500959, 1.14386766],
       [1.07859506, 1.23911969, 1.0320564 , 1.20501852, 1.0889301 ],
       [1.14441427, 1.13846608, 1.24859519, 1.07969696, 1.23429113],
       [1.2470494 , 1.07946085, 1.06212648, 1.04856761, 1.22987573],
       [1.19772957, 1.1840326 , 1.18056819, 1.17970864, 1.12018972]])

In [39]:
np.tan(ar)

array([[1.69405608, 1.8081613 , 1.60817443, 2.03993299, 2.19824229],
       [1.86490965, 2.90360642, 1.67302955, 2.61087261, 1.91210001],
       [2.20143409, 2.16710822, 2.99550024, 1.86985397, 2.85869787],
       [2.9801551 , 1.86879283, 1.79335629, 1.73754409, 2.81870371],
       [2.5549605 , 2.45533238, 2.43118751, 2.42525985, 2.06695514]])

In [44]:
np.sum(ar, axis=0)

array([5.70532858, 5.70669523, 5.53783105, 5.62800131, 5.81715433])

In [47]:
np.min(ar, axis=1)

array([1.01448479, 1.0320564 , 1.07969696, 1.04856761, 1.12018972])

In [48]:
ar

array([[1.03754028, 1.06561601, 1.01448479, 1.11500959, 1.14386766],
       [1.07859506, 1.23911969, 1.0320564 , 1.20501852, 1.0889301 ],
       [1.14441427, 1.13846608, 1.24859519, 1.07969696, 1.23429113],
       [1.2470494 , 1.07946085, 1.06212648, 1.04856761, 1.22987573],
       [1.19772957, 1.1840326 , 1.18056819, 1.17970864, 1.12018972]])

In [52]:
np.min(ar, axis=1)  

array([1.01448479, 1.0320564 , 1.07969696, 1.04856761, 1.12018972])

In [53]:
np.median(ar)

1.1384660795211043

In [54]:
np.std(ar)

0.07346324977375644

In [55]:
np.var(ar)

0.005396849067321325

In [58]:
ar 

array([[1.03754028, 1.06561601, 1.01448479, 1.11500959, 1.14386766],
       [1.07859506, 1.23911969, 1.0320564 , 1.20501852, 1.0889301 ],
       [1.14441427, 1.13846608, 1.24859519, 1.07969696, 1.23429113],
       [1.2470494 , 1.07946085, 1.06212648, 1.04856761, 1.22987573],
       [1.19772957, 1.1840326 , 1.18056819, 1.17970864, 1.12018972]])

In [71]:
ar[1:3, 2:5]

array([[1.0320564 , 1.20501852, 1.0889301 ],
       [1.24859519, 1.07969696, 1.23429113]])

In [73]:
ar[3:5,2:5]

array([[1.06212648, 1.04856761, 1.22987573],
       [1.18056819, 1.17970864, 1.12018972]])

In [74]:
np.short(ar)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [75]:
ar

array([[1.03754028, 1.06561601, 1.01448479, 1.11500959, 1.14386766],
       [1.07859506, 1.23911969, 1.0320564 , 1.20501852, 1.0889301 ],
       [1.14441427, 1.13846608, 1.24859519, 1.07969696, 1.23429113],
       [1.2470494 , 1.07946085, 1.06212648, 1.04856761, 1.22987573],
       [1.19772957, 1.1840326 , 1.18056819, 1.17970864, 1.12018972]])

In [76]:
np.sort(ar)


array([[1.01448479, 1.03754028, 1.06561601, 1.11500959, 1.14386766],
       [1.0320564 , 1.07859506, 1.0889301 , 1.20501852, 1.23911969],
       [1.07969696, 1.13846608, 1.14441427, 1.23429113, 1.24859519],
       [1.04856761, 1.06212648, 1.07946085, 1.22987573, 1.2470494 ],
       [1.12018972, 1.17970864, 1.18056819, 1.1840326 , 1.19772957]])

In [77]:
ar = ar+2


In [78]:
ar

array([[3.03754028, 3.06561601, 3.01448479, 3.11500959, 3.14386766],
       [3.07859506, 3.23911969, 3.0320564 , 3.20501852, 3.0889301 ],
       [3.14441427, 3.13846608, 3.24859519, 3.07969696, 3.23429113],
       [3.2470494 , 3.07946085, 3.06212648, 3.04856761, 3.22987573],
       [3.19772957, 3.1840326 , 3.18056819, 3.17970864, 3.12018972]])

In [79]:
np.short(ar)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int16)

In [80]:
ar.T

array([[3.03754028, 3.07859506, 3.14441427, 3.2470494 , 3.19772957],
       [3.06561601, 3.23911969, 3.13846608, 3.07946085, 3.1840326 ],
       [3.01448479, 3.0320564 , 3.24859519, 3.06212648, 3.18056819],
       [3.11500959, 3.20501852, 3.07969696, 3.04856761, 3.17970864],
       [3.14386766, 3.0889301 , 3.23429113, 3.22987573, 3.12018972]])

In [81]:
 ar =np.array([23,34,44,65,34])


In [82]:
ar

array([23, 34, 44, 65, 34])

In [85]:
arr1= np.insert(ar,0,[20,29,28])
arr1

array([20, 29, 28, 23, 34, 44, 65, 34])

In [86]:
arr2 = np.delete(arr1,0)

In [87]:
arr2

array([29, 28, 23, 34, 44, 65, 34])

In [89]:
arrc = arr2.copy()
arrc

array([29, 28, 23, 34, 44, 65, 34])

In [92]:
arrd = np.vstack((arr2,arrc))
arrd

array([[29, 28, 23, 34, 44, 65, 34],
       [29, 28, 23, 34, 44, 65, 34]])

In [97]:
arrd = np.insert(arrd,2,[12,21,21,21])
arrd

array([12, 21, 12, 21, 21, 21, 21, 21, 29, 12, 21, 21, 21, 28, 23, 34, 44,
       65, 34, 29, 28, 23, 34, 44, 65, 34])

In [98]:
arrd = np.vstack((arr2,arrc))
arrd

array([[29, 28, 23, 34, 44, 65, 34],
       [29, 28, 23, 34, 44, 65, 34]])

In [102]:
arr = np.vstack((arrd,arrc))
arr

array([[29, 28, 23, 34, 44, 65, 34],
       [29, 28, 23, 34, 44, 65, 34],
       [29, 28, 23, 34, 44, 65, 34],
       [29, 28, 23, 34, 44, 65, 34],
       [29, 28, 23, 34, 44, 65, 34]])

In [103]:
np.unique(arr)

array([23, 28, 29, 34, 44, 65])

In [108]:
uniques, counts = np.unique(arr, return_counts= True)
print(uniques)
print(counts)

[23 28 29 34 44 65]
[ 5  5  5 10  5  5]


In [111]:
arr1= np.array([2,5,6,6])
arr2= np.array([3,5,6,7])
print(np.intersect1d(arr1,arr2))
print(np.union1d(arr1,arr2))
print(np.setxor1d(arr1,arr2))

[5 6]
[2 3 5 6 7]
[2 3 7]
